#!/usr/bin/env bash
# Generate deploy/.env.migration from the process environment.
#
#   ./deploy/write-env-migration.sh
#
# Why this exists: the application secrets have to reach the EC2 box, but they
# must never appear in the git history, in a commit, or in a chat transcript.
# Setting them as environment variables (in your cloud environment config, or
# exported in your local shell) and generating the file from there keeps them
# out of all three.
#
# Prints only variable NAMES and whether each is set — never a value.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/deploy/.env.migration"

# ANTHROPIC_API_KEY is required unless you explicitly opt out with
# DEPLOY_WITHOUT_AI_KEY=1. Opting out is a supported state, not a fudge: with no
# key every AI call fails closed and uploads route to human triage, which is the
# documented degradation (docs/HANDOFF_PROMPT.md §2). Everything that does not
# call Anthropic — intake, the registries, review queues, price ledger, template
# emission, the whole UI — is unaffected. The key can be added later by updating
# the SSM parameter and restarting; no image rebuild.
REQUIRED=(MONGODB_URI)
[ "${DEPLOY_WITHOUT_AI_KEY:-0}" = "1" ] || REQUIRED+=(ANTHROPIC_API_KEY)
OPTIONAL=(
  CLOUDINARY_CLOUD_NAME CLOUDINARY_API_KEY CLOUDINARY_API_SECRET
  CLOUDINARY_FOLDER CLOUDINARY_UNSIGNED_PRESET CLOUDINARY_AVATAR_FOLDER
  ADLM_AI_URL ADLM_AI_TOKEN CORS_ORIGINS
)
# Written when present, whether or not it was demanded above — opting out of the
# check must not discard a key that happens to be set. Spelled as an `if` and
# not `[ … ] && …`, which under `set -e` exits the script when the test is false.
if [ "${DEPLOY_WITHOUT_AI_KEY:-0}" = "1" ]; then
  OPTIONAL+=(ANTHROPIC_API_KEY)
fi

MISSING=0
for v in "${REQUIRED[@]}"; do
  [ -n "${!v:-}" ] || { echo "MISSING (required): $v"; MISSING=1; }
done
[ "$MISSING" -eq 0 ] || {
  echo
  echo "Set the missing variables in your cloud environment configuration"
  echo "(claude.ai/code -> environment settings -> environment variables),"
  echo "then start a fresh session and re-run this."
  exit 1
}

umask 077                      # 0600 — not world-readable
{
  echo "# Generated by deploy/write-env-migration.sh — DO NOT COMMIT."
  echo "# Gitignored. Copied to the EC2 box by go-live.sh."
  echo "NODE_ENV=production"
  for v in "${REQUIRED[@]}" "${OPTIONAL[@]}"; do
    [ -n "${!v:-}" ] && printf '%s=%s\n' "$v" "${!v}"
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines, mode $(stat -c '%a' "$OUT"))"
echo
for v in "${REQUIRED[@]}" "${OPTIONAL[@]}"; do
  if [ -n "${!v:-}" ]; then printf '  set      %s\n' "$v"; else printf '  skipped  %s\n' "$v"; fi
done

# Refuse to leave a secret file tracked by git.
if ! git -C "$ROOT" check-ignore -q deploy/.env.migration; then
  echo
  echo "FATAL: deploy/.env.migration is NOT gitignored. Removing it."
  rm -f "$OUT"
  exit 1
fi
echo
echo "confirmed gitignored — safe."
